services:
  - type: web
    name: breathe-esg
    runtime: python
    pythonVersion: "3.11.7"
    buildCommand: cd backend && bash build.sh
    startCommand: cd backend && gunicorn esg.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
