services:
  - type: web
    name: breathe-esg
    runtime: python
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: gunicorn esg.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
